try{
    throw new Error("Fehler...");
}
catch(err){
    console.log(err.message);
}
finally{
    
}